name: CI

on: push


jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      API: http://localhost:8000/api/v1
    steps:
      - uses: actions/checkout@v2

      - name: Config
        run: echo -n "$API" > config/api-url.txt

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: pb
